# Generated by Django 2.2 on 2019-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190719_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='rubric',
            field=models.CharField(choices=[('all', 'all'), ('travel', 'Travel'), ('coffee_country', 'Coffee country'), ('hand_made', 'Hand made'), ('places_and_events', 'Places and events')], default='all', max_length=100, verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название статьи'),
        ),
    ]
