# Generated by Django 2.2 on 2019-07-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190719_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rubric',
            field=models.CharField(choices=[('all', 'Все'), ('travel', 'Путешествия'), ('coffee_country', 'Страна Кофе'), ('hand_made', 'Hand made'), ('places_and_events', 'Места и события')], default='all', max_length=100, verbose_name='Рубрика'),
        ),
    ]
